name: propertycp
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  awesome_dialog: ^3.1.0
  cached_network_image: any
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  dropdown_button2: ^2.3.9
  easy_autocomplete: ^1.6.0
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flashy_tab_bar2: ^0.0.6
  flutter:
    sdk: flutter
  flutter_html: any
  flutter_svg: ^2.0.7
  google_fonts: any
  image_picker: ^1.0.1
  intl: ^0.18.1
  introduction_screen: ^3.1.8
  line_awesome_flutter: ^2.0.0
  otp_text_field: ^1.1.3
  path_provider: ^2.0.15
  pdf: ^3.10.4
  printing: ^5.11.0
  provider: ^6.0.5
  share_plus: ^7.1.0
  shared_preferences: ^2.2.0
  string_validator: ^1.0.0
  timeago: ^3.4.0
  url_launcher: ^6.1.11
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/svgs/

flutter_native_splash:
  image: assets/logos/splash_with_branding.png
  color: "#ffffff"
  android_12:
    image: assets/logos/logo.png
    color: "#ffffff"
  web_image_mode: cover
  android_gravity: fill
  ios_content_mode: scaleToFill
# flutter pub run flutter_native_splash:create
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logos/logo.png"
  adaptive_icon_background: "#ffffff"
